# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LottoMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LottoMate
  pod 'FlexLayout'
  pod 'PinLayout'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RxCocoa'
  pod 'SwiftSoup'
  pod 'RxGesture'
  pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
  pod 'GoogleSignIn'
  pod 'naveridlogin-sdk-ios'
  pod 'NMapsMap'
  pod 'ReactorKit'


  target 'LottoMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LottoMateUITests' do
    # Pods for testing
  end

 
  project 'LottoMate', 'NoServerDebug' => :debug

end
